"""Model-free, fixture-driven tests for `clozn adopt ollama` (clozn.cli.commands.adopt).

No real Ollama process and no real network are ever used: `urllib.request.urlopen` is monkeypatched to
answer a small in-memory fake registry (see _FakeOllama), and "Ollama's blob" is a real temp file on
disk holding a hand-built synthetic GGUF (same technique tests/test_fit_planner.py uses for
parse_gguf_header -- duplicated here in miniature so this file stays self-contained).

These tests are also the binding-condition proof the coordinator required:
  * test_undo_restores_source_untouched_and_byte_identical  -- undo actually restores prior state, not
    just a docstring claim.
  * test_undo_refuses_when_ollama_side_reference_is_gone     -- the GC case refuses cleanly and leaves
    Clozn's own copy in place; it never silently succeeds.
  * test_apply_never_writes_under_the_fake_ollama_directory  -- adoption never writes into "Ollama"
    storage, proven by snapshotting that whole directory tree before and after.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import os
import struct
import urllib.error
import urllib.request
from pathlib import Path

import pytest

from clozn.cli.commands import adopt


# --------------------------------------------------------------------------------- synthetic GGUF bytes
# Minimal hand-built GGUF (magic + version + counts + a few metadata KVs + one tensor info), same shape
# tests/test_fit_planner.py's own _build_gguf_bytes produces -- reimplemented here in miniature so this
# file has no cross-test-module import dependency.

def _u32(v): return struct.pack("<I", v)
def _u64(v): return struct.pack("<Q", v)
def _str(s):
    b = s.encode("utf-8")
    return _u64(len(b)) + b


def _kv_u32(key, v):
    return _str(key) + _u32(4) + _u32(v)


def _kv_str(key, v):
    return _str(key) + _u32(8) + _str(v)


def _tensor_info(name, dims, ggml_type, offset):
    out = _str(name) + _u32(len(dims))
    for d in dims:
        out += _u64(d)
    return out + _u32(ggml_type) + _u64(offset)


def _synthetic_gguf_bytes(arch="qwen2") -> bytes:
    tensors = [("blk.0.attn_q.weight", [8, 8], 0, 0)]
    kvs = b"".join([
        _kv_str("general.architecture", arch),
        _kv_u32("general.file_type", 1),
        _kv_u32(f"{arch}.block_count", 2),
        _kv_u32(f"{arch}.context_length", 4096),
        _kv_u32(f"{arch}.embedding_length", 8),
        _kv_u32(f"{arch}.attention.head_count", 2),
        _kv_u32(f"{arch}.attention.head_count_kv", 2),
    ])
    body = _u32(3) + _u64(len(tensors)) + _u64(7) + kvs + b"".join(_tensor_info(*t) for t in tensors)
    return b"GGUF" + body + (b"\x00" * 4096)   # padding so it looks like a real (if tiny) weight file


# ----------------------------------------------------------------------------------------- fake ollama

class _FakeResponse:
    def __init__(self, payload):
        self._body = json.dumps(payload).encode("utf-8")

    def __enter__(self):
        return self

    def __exit__(self, *_exc):
        return False

    def read(self):
        return self._body


class _FakeOllama:
    """Answers /api/version, /api/tags, /api/show for one host; anything else raises like a closed
    port would."""

    def __init__(self, host="http://127.0.0.1:11434", version="0.6.2"):
        self.host = host
        self.version = version
        self.models: dict[str, dict] = {}   # name -> {"tags_entry": {...}, "show": {...}}

    def add_model(self, name, *, blob_path=None, digest="sha256:" + "a" * 64, details=None):
        tags_entry = {"name": name, "model": name, "digest": digest, "size": 123,
                     "details": details or {}}
        modelfile = '# Modelfile generated by "ollama show"\n'
        if blob_path is not None:
            modelfile += f"FROM {blob_path}\n"
        show = {"modelfile": modelfile, "template": "{{ .Prompt }}", "parameters": "",
               "details": details or {}}
        self.models[name] = {"tags_entry": tags_entry, "show": show}

    def install(self, monkeypatch):
        def _fake(request, timeout=None):
            url = request.full_url if isinstance(request, urllib.request.Request) else str(request)
            if not url.startswith(self.host):
                raise urllib.error.URLError("connection refused")
            if url.endswith("/api/version"):
                return _FakeResponse({"version": self.version})
            if url.endswith("/api/tags"):
                return _FakeResponse({"models": [m["tags_entry"] for m in self.models.values()]})
            if url.endswith("/api/show"):
                body = json.loads(request.data.decode("utf-8"))
                name = body["name"]
                if name not in self.models:
                    raise urllib.error.HTTPError(url, 404, "not found", None, None)
                return _FakeResponse(self.models[name]["show"])
            raise urllib.error.URLError(f"unhandled path: {url}")
        monkeypatch.setattr(urllib.request, "urlopen", _fake)


def _args(**overrides):
    base = dict(app="ollama", model=None, host=None, link=False, copy=False, connect=None,
               url="http://127.0.0.1:8080/v1", api_key="local-clozn",
               client_model_label="clozn-local", dry_run=False, undo=False, json=False)
    base.update(overrides)
    return argparse.Namespace(**base)


@pytest.fixture
def home(tmp_path, monkeypatch):
    """Points clozn.cli.main.HOME at an isolated dir for this test AND at the Ollama fake's own 'blob
    store' directory -- both under tmp_path, so hard-link creation (same-volume requirement) works in
    CI regardless of where the OS temp dir actually lives relative to a real user profile."""
    import clozn.cli.main as ctx
    home_dir = tmp_path / "clozn-home"
    home_dir.mkdir()
    monkeypatch.setattr(ctx, "HOME", str(home_dir))
    return home_dir


@pytest.fixture
def ollama_blob(tmp_path):
    blob_dir = tmp_path / "fake-ollama-blobs"
    blob_dir.mkdir()
    blob_path = blob_dir / "sha256-deadbeef"
    blob_path.write_bytes(_synthetic_gguf_bytes())
    return blob_path


# ---------------------------------------------------------------------------------------- _find_model

def test_find_model_exact_match():
    models = [{"name": "a"}, {"name": "b"}]
    assert adopt._find_model(models, "a") == {"name": "a"}


def test_find_model_not_found_lists_available():
    with pytest.raises(ValueError, match="not found among Ollama's models: a, b"):
        adopt._find_model([{"name": "a"}, {"name": "b"}], "c")


def test_find_model_ambiguous_fuzzy_match():
    models = [{"name": "qwen2.5:7b"}, {"name": "qwen2.5:14b"}]
    with pytest.raises(ValueError, match="ambiguous"):
        adopt._find_model(models, "qwen")


# ------------------------------------------------------------------------------ _resolve_source_blob_path

def test_resolve_source_blob_path_finds_absolute_existing_path(tmp_path):
    blob = tmp_path / "blob"
    blob.write_bytes(b"x")
    text = f"FROM {blob}\nTEMPLATE \"\"\"x\"\"\"\n"
    assert adopt._resolve_source_blob_path(text) == str(blob)


def test_resolve_source_blob_path_none_when_from_is_another_tag():
    assert adopt._resolve_source_blob_path("FROM llama3:latest\n") is None


def test_resolve_source_blob_path_none_when_path_does_not_exist(tmp_path):
    assert adopt._resolve_source_blob_path(f"FROM {tmp_path / 'missing'}\n") is None


def test_resolve_source_blob_path_none_when_no_from_line():
    assert adopt._resolve_source_blob_path("TEMPLATE \"\"\"x\"\"\"\n") is None


def test_resolve_source_blob_path_none_when_modelfile_absent():
    assert adopt._resolve_source_blob_path(None) is None


# --------------------------------------------------------------------------------------- _describe_setup

def test_describe_setup_lists_models_and_aider_detection(monkeypatch, home):
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", details={"parameter_size": "7.6B", "quantization_level": "Q4_K_M"})
    ollama.install(monkeypatch)
    monkeypatch.setattr("shutil.which", lambda _n: None)

    report = adopt._describe_setup(_args())
    assert report["status"] == "described"
    assert report["discovery"]["found"] is True
    assert [m["name"] for m in report["models"]] == ["qwen2.5:7b-instruct"]
    assert report["applications"][0]["app"] == "aider"
    assert report["applications"][0]["connector_available"] is False


def test_describe_setup_reports_not_found_cleanly(monkeypatch, home, tmp_path):
    monkeypatch.delenv("OLLAMA_HOST", raising=False)
    monkeypatch.setattr(urllib.request, "urlopen",
                        lambda *a, **k: (_ for _ in ()).throw(urllib.error.URLError("refused")))
    monkeypatch.setattr(adopt.discovery, "known_storage_path", lambda: None)
    report = adopt._describe_setup(_args())
    assert report["discovery"]["found"] is False
    assert report["models"] == []


# ------------------------------------------------------------------------------------------------ dry-run

def test_dry_run_shows_plan_and_writes_nothing(monkeypatch, home, ollama_blob):
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)

    plan = adopt._build_plan(_args(model="qwen2.5:7b-instruct"))
    report = adopt._dry_run_report(plan)

    assert report["status"] == "dry_run"
    assert report["blocked"] is None
    assert report["reuse_method"] == "hard_link"
    assert report["source_blob_path"] == str(ollama_blob)
    assert report["registered_name"] == "ollama/qwen2.5:7b-instruct"
    assert report["engine_capability"] == {"level": "discovered", "architecture": "qwen2"}
    assert report["extra_disk_bytes"] == 0
    assert not Path(report["clozn_path"]).exists()
    assert not (home / "adopt").exists()


def test_build_plan_resolves_exact_manifest_model_layer(monkeypatch, home, ollama_blob, tmp_path):
    ollama = _FakeOllama()
    model_name = "qwen2.5:7b-instruct"
    ollama.add_model(model_name, blob_path=None)
    ollama.install(monkeypatch)
    root = tmp_path / "ollama-models"
    digest = hashlib.sha256(ollama_blob.read_bytes()).hexdigest()
    blob = root / "blobs" / f"sha256-{digest}"
    blob.parent.mkdir(parents=True)
    blob.write_bytes(ollama_blob.read_bytes())
    manifest = root / "manifests" / "registry.ollama.ai" / "library" / "qwen2.5" / "7b-instruct"
    manifest.parent.mkdir(parents=True)
    manifest.write_text(json.dumps({"layers": [{
        "mediaType": "application/vnd.ollama.image.model",
        "digest": f"sha256:{digest}",
        "size": blob.stat().st_size,
    }]}), encoding="utf-8")
    monkeypatch.setattr(adopt.discovery, "known_storage_paths", lambda: [str(root)])

    plan = adopt._build_plan(_args(model=model_name))

    assert plan["blocked"] is None
    assert plan["blob_path"] == str(blob.resolve())
    assert plan["resolution"]["method"] == "manifest_model_layer"
    assert plan["resolution"]["blob_digest"] == f"sha256:{digest}"


def test_dry_run_reports_blocked_when_no_local_blob(monkeypatch, home):
    ollama = _FakeOllama()
    ollama.add_model("cloud-only:latest", blob_path=None)
    ollama.install(monkeypatch)

    plan = adopt._build_plan(_args(model="cloud-only:latest"))
    report = adopt._dry_run_report(plan)
    assert report["blocked"] is not None
    assert "no local GGUF blob" in report["blocked"]
    assert report["reuse_method"] is None


def test_dry_run_reports_blocked_for_unparseable_gguf(monkeypatch, home, tmp_path):
    bad_blob = tmp_path / "not-a-gguf"
    bad_blob.write_bytes(b"NOTGGUF" + b"\x00" * 100)
    ollama = _FakeOllama()
    ollama.add_model("broken:latest", blob_path=str(bad_blob))
    ollama.install(monkeypatch)

    plan = adopt._build_plan(_args(model="broken:latest"))
    report = adopt._dry_run_report(plan)
    assert report["blocked"] is not None
    assert "could not be parsed as a GGUF" in report["blocked"]


def test_build_plan_raises_when_ollama_not_found(monkeypatch, home):
    monkeypatch.delenv("OLLAMA_HOST", raising=False)
    monkeypatch.setattr(urllib.request, "urlopen",
                        lambda *a, **k: (_ for _ in ()).throw(urllib.error.URLError("refused")))
    monkeypatch.setattr(adopt.discovery, "known_storage_path", lambda: None)
    with pytest.raises(ValueError, match="no Ollama installation found"):
        adopt._build_plan(_args(model="anything"))


# --------------------------------------------------------------------------------------------------- apply

def _snapshot(directory: Path) -> dict:
    return {str(p): p.read_bytes() for p in directory.rglob("*") if p.is_file()}


def test_apply_hard_link_creates_entry_and_transaction(monkeypatch, home, ollama_blob):
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)
    source_bytes = ollama_blob.read_bytes()

    plan = adopt._build_plan(_args(model="qwen2.5:7b-instruct"))
    report = adopt._apply(_args(model="qwen2.5:7b-instruct"), plan)

    assert report["status"] == "adopted"
    target = Path(report["clozn_path"])
    assert target.is_file()
    assert target.read_bytes() == source_bytes
    assert os.stat(target).st_nlink >= 2          # shares the inode with ollama_blob

    tx_path = Path(report["transaction_path"])
    document = json.loads(tx_path.read_text(encoding="utf-8"))
    from clozn import schemas
    schemas.validate(document, "clozn.adopt-ollama.v1")
    assert document["clozn"]["mode"] == "hard_link"
    assert document["ollama"]["model_name"] == "qwen2.5:7b-instruct"

    # source untouched
    assert ollama_blob.read_bytes() == source_bytes


def test_apply_hard_link_failure_suggests_copy_and_leaves_nothing_behind(monkeypatch, home, ollama_blob):
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)

    def _raise(*_a, **_k):
        raise OSError("simulated cross-device link failure")
    monkeypatch.setattr(os, "link", _raise)

    plan = adopt._build_plan(_args(model="qwen2.5:7b-instruct"))
    with pytest.raises(ValueError, match="--copy"):
        adopt._apply(_args(model="qwen2.5:7b-instruct"), plan)

    assert not Path(plan["clozn_path"]).exists()
    assert not (home / "adopt").exists()


def test_apply_never_writes_under_the_fake_ollama_directory(monkeypatch, home, ollama_blob):
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)
    ollama_dir = ollama_blob.parent
    before = _snapshot(ollama_dir)
    before_entries = sorted(os.listdir(ollama_dir))

    plan = adopt._build_plan(_args(model="qwen2.5:7b-instruct"))
    adopt._apply(_args(model="qwen2.5:7b-instruct"), plan)

    after = _snapshot(ollama_dir)
    after_entries = sorted(os.listdir(ollama_dir))
    assert before == after
    assert before_entries == after_entries


def test_apply_copy_mode_makes_an_independent_file(monkeypatch, home, ollama_blob):
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)

    plan = adopt._build_plan(_args(model="qwen2.5:7b-instruct", copy=True))
    report = adopt._apply(_args(model="qwen2.5:7b-instruct", copy=True), plan)

    target = Path(report["clozn_path"])
    assert target.read_bytes() == ollama_blob.read_bytes()
    assert os.stat(target).st_nlink == 1
    assert os.stat(target).st_ino != os.stat(ollama_blob).st_ino


def test_apply_is_idempotent_on_unchanged_reapply(monkeypatch, home, ollama_blob):
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)

    plan = adopt._build_plan(_args(model="qwen2.5:7b-instruct"))
    first = adopt._apply(_args(model="qwen2.5:7b-instruct"), plan)
    assert first["status"] == "adopted"

    plan2 = adopt._build_plan(_args(model="qwen2.5:7b-instruct"))
    second = adopt._apply(_args(model="qwen2.5:7b-instruct"), plan2)
    assert second["status"] == "unchanged"


def test_changed_ollama_tag_digest_cannot_reuse_stale_adoption(monkeypatch, home, ollama_blob):
    ollama = _FakeOllama()
    name = "qwen2.5:7b-instruct"
    ollama.add_model(name, blob_path=str(ollama_blob), digest="sha256:" + "a" * 64)
    ollama.install(monkeypatch)
    args = _args(model=name)
    adopt._apply(args, adopt._build_plan(args))

    ollama.models[name]["tags_entry"]["digest"] = "sha256:" + "b" * 64
    with pytest.raises(ValueError, match="already adopted"):
        adopt._apply(args, adopt._build_plan(args))


def test_qualify_success_is_recorded_after_safe_adoption(monkeypatch, home, ollama_blob):
    ollama = _FakeOllama()
    name = "qwen2.5:7b-instruct"
    ollama.add_model(name, blob_path=str(ollama_blob))
    ollama.install(monkeypatch)
    monkeypatch.setattr(adopt, "_run_qualification", lambda _plan: {
        "status": "passed",
        "capability": "core",
        "run_id": "run-qualified",
        "receipt_shape": "new",
        "warnings": [],
    })
    args = _args(model=name, qualify=True)

    report = adopt._apply(args, adopt._build_plan(args))
    transaction = json.loads(Path(report["transaction_path"]).read_text(encoding="utf-8"))

    assert report["qualification"]["status"] == "passed"
    assert transaction["qualification"]["run_id"] == "run-qualified"
    assert Path(report["clozn_path"]).is_file()


def test_qualification_failure_preserves_adoption_and_exact_undo(monkeypatch, home, ollama_blob):
    ollama = _FakeOllama()
    name = "qwen2.5:7b-instruct"
    ollama.add_model(name, blob_path=str(ollama_blob))
    ollama.install(monkeypatch)
    monkeypatch.setattr(adopt, "_run_qualification", lambda plan: {
        "status": "failed",
        "capability": "discovered",
        "error": "engine failed",
        "warnings": ["adoption preserved"],
        "undo_command": f"clozn adopt ollama --model {plan['model_name']} --undo",
    })
    args = _args(model=name, qualify=True)

    report = adopt._apply(args, adopt._build_plan(args))

    assert report["qualification"]["status"] == "failed"
    assert Path(report["clozn_path"]).is_file()
    assert report["undo_commands"]["adoption"] == (
        f"clozn adopt ollama --model {name} --undo"
    )


def test_apply_refuses_blocked_model(monkeypatch, home):
    ollama = _FakeOllama()
    ollama.add_model("cloud-only:latest", blob_path=None)
    ollama.install(monkeypatch)
    plan = adopt._build_plan(_args(model="cloud-only:latest"))
    with pytest.raises(ValueError, match="cannot adopt"):
        adopt._apply(_args(model="cloud-only:latest"), plan)


def test_apply_refuses_to_overwrite_unmanaged_file(monkeypatch, home, ollama_blob):
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)

    plan = adopt._build_plan(_args(model="qwen2.5:7b-instruct"))
    target = Path(plan["clozn_path"])
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_bytes(b"not managed by clozn adopt")

    with pytest.raises(ValueError, match="refusing to write"):
        adopt._apply(_args(model="qwen2.5:7b-instruct"), plan)


# ---------------------------------------------------------------------------------------------------- undo

def test_undo_restores_source_untouched_and_byte_identical(monkeypatch, home, ollama_blob):
    """The binding condition: undo must actually restore prior state, proven by assertion, not asserted
    only in a docstring."""
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)
    source_bytes_before = ollama_blob.read_bytes()
    ollama_dir_before = _snapshot(ollama_blob.parent)

    plan = adopt._build_plan(_args(model="qwen2.5:7b-instruct"))
    applied = adopt._apply(_args(model="qwen2.5:7b-instruct"), plan)
    target = Path(applied["clozn_path"])
    tx_path = Path(applied["transaction_path"])
    assert target.is_file() and tx_path.is_file()

    undone = adopt._undo(_args(model="qwen2.5:7b-instruct"))

    assert undone["status"] == "undone"
    assert not target.exists()
    assert not tx_path.exists()
    # prior state (the Ollama-side source) is exactly as it was, byte for byte
    assert ollama_blob.read_bytes() == source_bytes_before
    assert _snapshot(ollama_blob.parent) == ollama_dir_before


def test_undo_refuses_when_ollama_side_reference_is_gone(monkeypatch, home, ollama_blob):
    """The GC case: refuse cleanly, never silently succeed."""
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)

    plan = adopt._build_plan(_args(model="qwen2.5:7b-instruct"))
    applied = adopt._apply(_args(model="qwen2.5:7b-instruct"), plan)
    target = Path(applied["clozn_path"])

    # Simulate Ollama removing/GC'ing its own reference to the shared inode.
    ollama_blob.unlink()
    assert os.stat(target).st_nlink == 1

    with pytest.raises(ValueError, match="only one remaining hard link"):
        adopt._undo(_args(model="qwen2.5:7b-instruct"))

    # Undo must NOT have deleted Clozn's own copy -- it is now the last copy of this model's weights.
    assert target.is_file()


def test_undo_of_copy_mode_succeeds_even_if_source_is_gone(monkeypatch, home, ollama_blob):
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)

    plan = adopt._build_plan(_args(model="qwen2.5:7b-instruct", copy=True))
    applied = adopt._apply(_args(model="qwen2.5:7b-instruct", copy=True), plan)
    target = Path(applied["clozn_path"])
    ollama_blob.unlink()   # a copy owns its own bytes -- source disappearing changes nothing

    undone = adopt._undo(_args(model="qwen2.5:7b-instruct"))
    assert undone["status"] == "undone"
    assert not target.exists()


def test_undo_refuses_after_external_modification_of_adopted_copy(monkeypatch, home, ollama_blob):
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)

    plan = adopt._build_plan(_args(model="qwen2.5:7b-instruct", copy=True))
    applied = adopt._apply(_args(model="qwen2.5:7b-instruct", copy=True), plan)
    target = Path(applied["clozn_path"])
    target.write_bytes(b"tampered")

    with pytest.raises(ValueError, match="changed since it was adopted"):
        adopt._undo(_args(model="qwen2.5:7b-instruct"))
    assert target.read_bytes() == b"tampered"    # left alone, not clobbered either


def test_undo_without_model_requires_disambiguation_when_multiple(monkeypatch, home, tmp_path):
    ollama = _FakeOllama()
    blob_a = tmp_path / "a"; blob_a.write_bytes(_synthetic_gguf_bytes())
    blob_b = tmp_path / "b"; blob_b.write_bytes(_synthetic_gguf_bytes())
    ollama.add_model("model-a:latest", blob_path=str(blob_a))
    ollama.add_model("model-b:latest", blob_path=str(blob_b))
    ollama.install(monkeypatch)

    adopt._apply(_args(model="model-a:latest"), adopt._build_plan(_args(model="model-a:latest")))
    adopt._apply(_args(model="model-b:latest"), adopt._build_plan(_args(model="model-b:latest")))

    with pytest.raises(ValueError, match="more than one adopted model"):
        adopt._undo(_args())


def test_undo_without_any_transaction_is_a_clean_error(home):
    with pytest.raises(ValueError, match="no `clozn adopt ollama` transaction found"):
        adopt._undo(_args())


# --------------------------------------------------------------------------------------------- --connect

def test_apply_connect_aider_records_client_transaction(monkeypatch, home, ollama_blob, tmp_path):
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)
    monkeypatch.setattr("shutil.which", lambda _n: "/usr/bin/aider")

    args = _args(model="qwen2.5:7b-instruct", connect="aider")
    plan = adopt._build_plan(args)
    report = adopt._apply(args, plan)

    assert report["connect"]["status"] == "connected"
    document = json.loads(Path(report["transaction_path"]).read_text(encoding="utf-8"))
    assert len(document["client_transactions"]) == 1
    assert document["client_transactions"][0]["app"] == "aider"


def test_apply_connect_failure_does_not_undo_the_model_adoption(monkeypatch, home, ollama_blob):
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)
    monkeypatch.setattr("shutil.which", lambda _n: None)   # aider "not installed"

    args = _args(model="qwen2.5:7b-instruct", connect="aider")
    plan = adopt._build_plan(args)
    report = adopt._apply(args, plan)

    assert report["status"] == "adopted"
    assert Path(report["clozn_path"]).is_file()
    assert report["connect"]["status"] == "failed"


def test_apply_connect_failure_reports_the_requested_app(monkeypatch, home, ollama_blob):
    from clozn.cli.commands import _connector

    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)

    class FailingConnector:
        id = "open-webui"

        def detect(self):
            return _connector.Detection(installed=True, app=self.id)

        def plan(self, **_kwargs):
            return _connector.MutationPlan(
                app=self.id, status="dry_run", target=str(home / "client.env"),
                details={
                    "expected_prior_exists": False,
                    "after_sha256": "a" * 64,
                },
            )

        def apply(self, mutation, **_kwargs):
            assert mutation.app == self.id
            raise ValueError("simulated connector failure")

    monkeypatch.setattr(_connector, "connector_for", lambda _app: FailingConnector())
    args = _args(model="qwen2.5:7b-instruct", connect="open-webui")
    report = adopt._apply(args, adopt._build_plan(args))

    assert report["connect"] == {
        "status": "failed",
        "app": "open-webui",
        "error": "simulated connector failure",
    }


def test_cmd_adopt_returns_nonzero_when_connect_fails_but_adoption_succeeds(monkeypatch, home, ollama_blob, capsys):
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)
    monkeypatch.setattr("shutil.which", lambda _n: None)

    exit_code = adopt.cmd_adopt(_args(model="qwen2.5:7b-instruct", connect="aider", json=True))
    assert exit_code == 1
    printed = json.loads(capsys.readouterr().out)
    assert printed["status"] == "adopted"
    assert printed["connect"]["status"] == "failed"


# ---------------------------------------------------------------------------------------------- CLI wiring

def test_cmd_adopt_dry_run_json_round_trips(monkeypatch, home, ollama_blob, capsys):
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)

    exit_code = adopt.cmd_adopt(_args(model="qwen2.5:7b-instruct", dry_run=True, json=True))
    assert exit_code == 0
    printed = json.loads(capsys.readouterr().out)
    assert printed["status"] == "dry_run"
    assert not (home / "models").exists()
    assert not (home / "adopt").exists()


def test_try_flow_requires_explicit_yes_before_mutating(monkeypatch, home, ollama_blob, capsys):
    ollama = _FakeOllama()
    ollama.add_model("qwen2.5:7b-instruct", blob_path=str(ollama_blob))
    ollama.install(monkeypatch)
    args = _args(model="qwen2.5:7b-instruct", try_flow=True, yes=False, json=True)

    assert adopt.cmd_adopt(args) == 0
    report = json.loads(capsys.readouterr().out)
    assert report["requires_confirmation"] is True
    assert "--try --yes" in report["confirm_command"]
    assert not (home / "models").exists()


def test_add_subparser_registers_expected_flags():
    p = argparse.ArgumentParser()
    sub = p.add_subparsers()
    adopt.add_subparser(sub)
    args = p.parse_args([
        "adopt", "ollama", "--model", "x", "--try", "--yes", "--qualify",
        "--blob", str(Path.cwd() / "x.gguf"), "--json",
    ])
    assert args.app == "ollama"
    assert args.model == "x"
    assert args.try_flow is True
    assert args.yes is True
    assert args.qualify is True
    assert args.json is True
