"""Real ``ollama`` Python SDK conformance against Clozn's model-free gateway.

These tests exercise the public synchronous client against the real
``ThreadingHTTPServer`` handler; no model process or HTTP stubs are involved.  CI
pins the optional SDK separately.  Developer environments without it skip this
file, leaving the dependency-free Ollama wire-contract tests mandatory.

The compatibility target validated while adding this suite is ``ollama`` 0.6.x.
That release's Pydantic response models discard unknown additive response fields,
including Clozn's terminal ``clozn_run_id`` NDJSON extension.  The tests resolve
the journal directly in that case, but will also validate the ID if a future SDK
exposes it.  Non-streaming run IDs remain observable through the standard httpx
response-hook option accepted by ``ollama.Client``.
"""
from __future__ import annotations

import threading
import time
from http.server import ThreadingHTTPServer

import pytest


ollama = pytest.importorskip("ollama")

import clozn.settings as clozn_settings          # noqa: E402

import clozn.runs.store as runlog  # noqa: E402
from clozn.server import app as cs  # noqa: E402


class _Memory:
    memory_strength = 1.0
    rules = []
    prefix = None


class _Steer:
    strength = {}

    def active(self):
        return {}


class _Substrate:
    name = "engine"
    brain = None

    def __init__(self):
        self.memory = self._mem = _Memory()
        self.steer = _Steer()
        self._finish = "stop"
        self._stream_trace = []

    @staticmethod
    def _reply(messages):
        prompt = str((messages or [{}])[-1].get("content") or "")
        return "Generated by SDK." if "generate" in prompt.casefold() else "Chatted by SDK."

    def chat(self, messages, max_new=256, sample=True, trace_out=None, mem_out=None):
        reply = self._reply(messages)
        if mem_out is not None:
            mem_out.update(
                mode="prompt",
                applied=[],
                gate=None,
                assembled_messages=[dict(message) for message in messages],
                final_prompt=f"<sdk>{messages[-1]['content']}</sdk>",
            )
        if trace_out is not None:
            trace_out.append({"pos": 0, "token_id": 17, "piece": reply, "prob": 0.91})
        return reply

    def chat_stream(self, messages, max_new=256, mem_out=None, sample=True):
        prompt = str((messages or [{}])[-1].get("content") or "")
        reply = self._reply(messages)
        if mem_out is not None:
            mem_out.update(
                mode="prompt",
                applied=[],
                gate=None,
                assembled_messages=[dict(message) for message in messages],
                final_prompt=f"<sdk>{messages[-1]['content']}</sdk>",
            )
        if "cancel" in prompt.casefold():
            # Large, paced pieces keep the real socket open long enough for the SDK generator's close()
            # to reach the server before generation naturally completes.
            pieces = ["x" * 8192 for _ in range(100)]
        else:
            midpoint = len(reply) // 2
            pieces = [reply[:midpoint], reply[midpoint:]]
        self._stream_trace = [
            {"pos": pos, "token_id": 20 + pos, "piece": piece, "prob": 0.8 - pos / 10}
            for pos, piece in enumerate(pieces)
        ]
        for piece in pieces:
            if "cancel" in prompt.casefold():
                time.sleep(0.01)
            yield piece

    def last_finish_reason(self):
        return self._finish

    def last_stream_trace(self):
        return list(self._stream_trace)

    def run_meta(self):
        return {"model_id": "clozn-sdk-test", "sampler_mode": "greedy", "temperature": 0.0}


class _Engine:
    def health(self):
        return {"model": "C:/models/clozn-sdk-test.Q4_K_M.gguf", "model_sha256": "a" * 64}


@pytest.fixture
def ollama_gateway(tmp_path, monkeypatch):
    substrate = _Substrate()
    monkeypatch.setattr(runlog, "RUNS_DIR", str(tmp_path / "runs"))
    monkeypatch.setattr(clozn_settings, "SETTINGS_PATH", str(tmp_path / "settings.json"))
    monkeypatch.setattr(cs, "SUB", substrate)
    monkeypatch.setattr(cs, "SUBNAME", "engine")
    monkeypatch.setattr(cs, "ENGINE", _Engine())
    server = ThreadingHTTPServer(("127.0.0.1", 0), cs.make_handler())
    thread = threading.Thread(target=server.serve_forever, daemon=True)
    thread.start()
    try:
        yield f"http://127.0.0.1:{server.server_port}"
    finally:
        server.shutdown()
        server.server_close()
        thread.join(timeout=5)


def _runs_by_operation():
    return {
        run["meta"]["ollama_operation"]: run
        for run in runlog.iter_runs()
        if run.get("meta", {}).get("compatibility_api") == "ollama"
    }


def _assert_exposed_run_id(response, expected):
    """Validate the terminal extension when the installed SDK preserves unknown fields."""
    run_id = getattr(response, "clozn_run_id", None)
    if run_id is not None:
        assert run_id == expected["id"]
        assert runlog.get_run(run_id) == expected


def test_real_ollama_client_lists_gateway_tags(ollama_gateway):
    client = ollama.Client(host=ollama_gateway, timeout=5.0)

    listed = client.list()

    assert len(listed.models) == 1
    model = listed.models[0]
    assert model.model == "clozn-sdk-test.Q4_K_M"
    assert model.digest == f"sha256:{'a' * 64}"
    assert model.size == 0


def test_real_ollama_client_nonstream_chat_and_generate_are_journaled(ollama_gateway):
    response_run_ids = []

    def capture_run_id(response):
        if run_id := response.headers.get("X-Clozn-Run-Id"):
            response_run_ids.append(run_id)

    client = ollama.Client(
        host=ollama_gateway,
        timeout=5.0,
        event_hooks={"response": [capture_run_id]},
    )
    chat = client.chat(
        model="clozn-sdk-test",
        messages=[{"role": "user", "content": "Please chat"}],
        stream=False,
        options={"num_predict": 8, "temperature": 0},
    )
    generated = client.generate(
        model="clozn-sdk-test",
        system="Be terse.",
        prompt="Please generate",
        stream=False,
        options={"num_predict": 9, "temperature": 0},
    )

    assert chat.message.role == "assistant"
    assert chat.message.content == "Chatted by SDK."
    assert chat.done is True
    assert generated.response == "Generated by SDK."
    assert generated.done is True

    runs = _runs_by_operation()
    assert set(runs) == {"chat", "generate"}
    assert len(runlog.iter_runs()) == 2
    assert response_run_ids == [runs["chat"]["id"], runs["generate"]["id"]]
    assert len(set(response_run_ids)) == 2
    assert runs["chat"]["source"] == "ollama_api"
    assert runs["chat"]["model"] == "clozn-sdk-test"
    assert runs["chat"]["prompt_summary"] == "Please chat"
    assert runs["chat"]["response"] == "Chatted by SDK."
    assert runs["chat"]["trace"]["tokens"] == ["Chatted by SDK."]
    assert runs["generate"]["prompt_summary"] == "Please generate"
    assert runs["generate"]["response"] == "Generated by SDK."
    _assert_exposed_run_id(chat, runs["chat"])
    _assert_exposed_run_id(generated, runs["generate"])


def test_real_ollama_client_streams_chat_and_generate_with_coherent_terminal_runs(ollama_gateway):
    client = ollama.Client(host=ollama_gateway, timeout=5.0)

    chat_chunks = list(client.chat(
        model="clozn-sdk-test",
        messages=[{"role": "user", "content": "Please chat"}],
        stream=True,
        options={"temperature": 0},
    ))
    generate_chunks = list(client.generate(
        model="clozn-sdk-test",
        prompt="Please generate",
        stream=True,
        options={"temperature": 0},
    ))

    assert "".join(chunk.message.content or "" for chunk in chat_chunks) == "Chatted by SDK."
    assert chat_chunks[-1].done is True
    assert "".join(chunk.response or "" for chunk in generate_chunks) == "Generated by SDK."
    assert generate_chunks[-1].done is True

    runs = _runs_by_operation()
    assert set(runs) == {"chat", "generate"}
    assert len(runlog.iter_runs()) == 2
    assert runs["chat"]["response"] == "Chatted by SDK."
    assert "".join(runs["chat"]["trace"]["tokens"]) == "Chatted by SDK."
    assert runs["generate"]["response"] == "Generated by SDK."
    assert "".join(runs["generate"]["trace"]["tokens"]) == "Generated by SDK."
    assert runs["chat"]["finish_reason"] == "stop"
    assert runs["generate"]["finish_reason"] == "stop"
    _assert_exposed_run_id(chat_chunks[-1], runs["chat"])
    _assert_exposed_run_id(generate_chunks[-1], runs["generate"])


def test_real_ollama_client_receives_typed_400_for_unsupported_format(ollama_gateway):
    client = ollama.Client(host=ollama_gateway, timeout=5.0)

    with pytest.raises(ollama.ResponseError) as caught:
        client.chat(
            model="clozn-sdk-test",
            messages=[{"role": "user", "content": "Return JSON"}],
            format="json",
        )

    assert caught.value.status_code == 400
    assert "'format'" in caught.value.error
    assert runlog.iter_runs() == []


def test_real_ollama_client_close_cancels_and_journals_partial_stream(ollama_gateway):
    client = ollama.Client(host=ollama_gateway, timeout=5.0)
    stream = client.chat(
        model="clozn-sdk-test",
        messages=[{"role": "user", "content": "Please cancel this stream"}],
        stream=True,
    )
    first = next(stream)
    assert first.message.content
    stream.close()

    deadline = time.monotonic() + 5
    rows = []
    while time.monotonic() < deadline:
        rows = runlog.iter_runs()
        if rows:
            break
        time.sleep(0.02)
    client.close()
    assert len(rows) == 1
    assert rows[0]["meta"]["stream_failure"] == "client_disconnected"
    assert "client disconnected mid-stream" in rows[0]["error"]
    assert rows[0]["finish_reason"] is None
